### PR TITLE
Python based bootloader support and dfureset

### PR DESCRIPTION
**Pull request by trentgill**
`make pydfu` wraps the crow binary into a dfu package, then uploads using `pydfu.py` from [micropython](https://github.com/micropython/micropython) project.

Amazingly it's the fastest upload i've ever seen to a stm32 chip!

`make dfureset` attempts to send the `^^b` command to a connected crow. assumes port `/dev/ttyACM0` so it will only work on ubuntu right now.

`make dfureset pydfu` will build the firmware, reset to bootloader mode, and upload to memory.

//

@tehn the make recipe for `pydfu` is all it took to get the firmware to flash. it just relies upon `util/pydfu.py`. i'll need to update the git release to build .dfu file.

would be great if you could just try and build & upload the firmware with these new commands!

### CODE REVIEW

**Comment by tehn** [comment]
whoa! you did it! yes, will test it out.

**Comment by tehn** [comment]
just a forward reminder note:

```
pip install pyusb
```

(there's also a `usb` package, which is confusing)

**Review by tehn — APPROVED** [review]

**Comment by tehn** [comment]
i don't recall exactly but maybe druid installation has dependency checking? so that install can just take care of it...

**Comment by trentgill** [comment]
yes definitely druid has auto dependency handling (it already does it for the TUI library).

just checked and it looks like a one-line addition here https://github.com/monome/druid/blob/3541aab071b507c8bfc82a17deb52ec27db61bd5/setup.py#L35

**Pull request merged**
