### PR TITLE
change_handler now passes state as a bool

### LINKED ISSUE #143: input.change function returns number (should return bool)
would make interaction with held{} more elegant

### PR DESCRIPTION
**Pull request by trentgill**
fixes #143 

likely causes some new bugs in both monome/norns but also the max object

### CODE REVIEW

**Comment by tehn** [comment]
ha should've tested on hardware first:

```
[string "local _crow = {}..."]:37: bad argument #3 to 'tell' (string expected, got boolean)
crow receive: error: input change
```

**Comment by trentgill** [comment]
aye.. yes sorry. will fix shortly.

**Comment by tehn** [comment]
lualink.c fix i think

**Comment by trentgill** [comment]
hrmmm.. seems like `luaL_checkstring()` will coerce a number to a string, but not a boolean :/ will just convert to a string in the input.change event-handler i think.

**Pull request merged**
