### PR TITLE
Strip debug info - reduces RAM usage

### PR DESCRIPTION
**Pull request by trentgill**
This PR changes the way lua libs are loaded on crow. All debug info is stripped, so errors that happen in the core libs don't have line numbers and local var names.

I think we can justify this bc it's rare for an end-user to see stack trace errors from within the core libs. Generally errors are syntax based, or from incorrect args, most of which explicitly show error messages. It seems unlikely that a user would see an error message from a lua lib, and go find the source and track down the line where it happened.

The main challenge is when developing new lua libs. If this turns out to be an issue, it would be easy to add a flag to the libraries to state whether they should strip debug info or not.

Dramatically reduces RAM usage (110 -> 72kB for the THREE branch). Not a complete solution for #390 but certainly enough to make the `THREE` branch realistic.

### CODE REVIEW

**Comment by ngwese** [comment]
Would the change mean that a user script passing an incorrect value into a core library function would not get any illuminating information about where in the core lib something went wrong?

I would worry that this takes away end user usability.

**Comment by trentgill** [comment]
@ngwese There is still some illuminating information. From the `luac` docs:

> strip  debug  information  before  writing  the  output file.  This saves some space in very large chunks, but if errors occur when running a stripped chunk, then the error messages may not contain the full information they usually do.  In particular, line numbers and names of local variables are lost.

So you should still get function names at least. I just started entering a bunch of incorrect code into the REPL, and realized that pretty much everything I could think of that was wrong either failed silently, or with a `repl:1: attempt to index a nil value (field '?')` even on the main branch.

Basically I don't have a good model of what typical scripting errors look like, so it's really hard for me to say whether the error messages will be less informative. Maybe you have some pointers on how to model typical error states?

---

Actually reading that `luac` line again, the only time we "run the stripped chunk" is when we load it (when crow starts up). Maybe I'm being pedantic though, and it just means whenever that code is called at runtime?

I will say that even when there are line-number errors, they are already different from the source files bc of how we strip the whitespace & comments at compile time.

**Comment by ngwese** [comment]
Unfortunately I’m not a good data point regarding the development experience on crow. My setup isn’t conducive to it as the synth is far from a computer these days. My comment/question was largely motivated by my initial experience with crow - I found debugging harder than on norns and the error messages less descriptive. If the UX after stripping this into isn’t dramatically different than before I guess it isn’t a big deal.

**Review by tehn — APPROVED** [review]
after a long chat with trent with further explanation and examples i'm convinced this won't hurt the user experience at all. the RAM benefit is massive, so i'm going to merge this and keep my eyes out for any complaints about difficulty debugging.

debug info will be full/intact for the user script itself, and we concluded it was very difficult (basically impossible) to create a meaningful error that needed core lib traces--- and i'm not sure this actually helps users (often on norns the deeper trace is very confusing TBH).

**Pull request merged**
